version: '3.4'

services:
  daprcounter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - service-network
  daprcounter-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
     "-app-id", "daprcounter",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - daprcounter
    network_mode: "service:daprcounter"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - service-network
networks:
    service-network:
